# Generated by Django 3.2.25 on 2024-11-09 19:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('items', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='_trigger_scrape',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='product',
            name='trigger_scrape',
            field=models.BooleanField(default=False),
        ),
    ]
